#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [27]:
n = [10,30,60,90,120]
print(n)

[10, 30, 60, 90, 120]


In [28]:
type(n)

list

In [29]:
n

[10, 30, 60, 90, 120]

In [30]:
n.append(45) ## adds the given integer in the list
print(n)

[10, 30, 60, 90, 120, 45]


In [31]:
n.extend([18,333]) ## adds multiple numbers in the given list
print(n)

[10, 30, 60, 90, 120, 45, 18, 333]


In [32]:
n.insert(2,20) ## inserts the number at the given postion
print(n)

[10, 30, 20, 60, 90, 120, 45, 18, 333]


In [33]:
n.remove(10) ## removes the specific number
print(n)

[30, 20, 60, 90, 120, 45, 18, 333]


In [34]:
n.pop() ## removes the last element in the list
print(n)

[30, 20, 60, 90, 120, 45, 18]


In [36]:
print(n.index(30)) ## shows the position of the given number in the list

0


In [39]:
print(n.count(120)) ## count how many times the values is appeared in the list

1


In [40]:
n.sort() ## sort the list in the ascending order
print(n)

[18, 20, 30, 45, 60, 90, 120]


In [41]:
n.reverse() ## reverse the given list
print(n)

[120, 90, 60, 45, 30, 20, 18]


In [42]:
n.clear() ## clear all the number/ elements in the list
print(n)

[]


### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [50]:
students = ('Shardul','Shreyash','Raj')
print(students)

('Shardul', 'Shreyash', 'Raj')


In [51]:
type(students)

tuple

In [52]:
students[1]='ninad'

TypeError: 'tuple' object does not support item assignment

#### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [54]:
A = {10,20,30,40,50,60,70,80,10,30,50,70}
print(A)

{70, 40, 10, 80, 50, 20, 60, 30}


#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [59]:
dict = {
    "name":"shardul",
    "age": 23,
    "city":"Amravati"
}
print(dict)

{'name': 'shardul', 'age': 23, 'city': 'Amravati'}


In [61]:
dict["age"]=24
dict["Email"]= "shardultidke@gmail.com"
print(dict)

{'name': 'shardul', 'age': 24, 'city': 'Amravati', 'Email': 'shardultidke@gmail.com'}


### Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [62]:
age = 23
if age >= 18:
    print("You are eligible for voting")
else:
    print("You are not eligible for voting")

You are eligible for voting


### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [64]:
marks = 49
if marks >= 90:
    print("Grade:A")
elif marks >=75:
    print("Grade:B")
elif marks >=50:
    print("Grade:C")
else:
    print("Failed")

Failed


### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [72]:
n = int(input("Enter Your number"))
number = n
if number > 0:
    print('Numebr is Positive')
    if number % 2 == 0:
        print("Number is Even")
    else:
        print("Number is Odd")
else:
    if number == 0:
        print("Number is zero")
    else:
        print("number is negative")

Enter Your number 0


Number is zero


### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [80]:
import numpy as np

In [77]:
scaler = np.array(5)
print(scaler)

5


In [75]:
one_dim = np.array([1,2,3,4,5])
print(one_dim)

[1 2 3 4 5]


In [87]:
two_dim=np.arange(10,70,10).reshape(2,3)
print(two_dim)

[[10 20 30]
 [40 50 60]]


### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [90]:
import numpy as np 
import random

In [98]:
a = np.random.randint(0,100, size=(4,4))

In [99]:
a

array([[46, 30,  6, 57],
       [ 2,  8, 75,  5],
       [99, 23,  6, 89],
       [69, 11, 90, 99]], dtype=int32)

### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [100]:
import numpy as np
import pandas as pd

In [101]:
two_dim=np.arange(1,10).reshape(3,3)

In [107]:
two_dim.ndim

2

In [105]:
df= pd.DataFrame(two_dim , columns=['A','B','C'])

In [106]:
df

,A,B,C
0,1,2,3
1,4,5,6
2,7,8,9


### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [138]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [139]:
df=pd.DataFrame({
    'Name':['Aman','Bob','chandan','david','eva','freddy','gagan','hugh','imad','jack'],
    'Age':[22,23,24,34,45,35,27,26,29,30],
    'city':['amravati','nagpur','wardha','asegaon','akola','washim','bhusawal','bangaluru','mumbai','chennai'],
    'salary':[35000,40000,45000,np.nan,50000,55000,np.nan,60000,65000,70000]
})

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   city    10 non-null     object 
 3   salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [141]:
df.describe()

,Age,salary
count,10.000000,8.000000
mean,29.500000,52500.000000
std,6.980131,12247.448714
min,22.000000,35000.000000
25%,24.500000,43750.000000
50%,28.000000,52500.000000
75%,33.000000,61250.000000
max,45.000000,70000.000000


In [142]:
df[['Name','city']]

,Name,city
0,Aman,amravati
1,Bob,nagpur
2,chandan,wardha
3,david,asegaon
4,eva,akola
5,freddy,washim
6,gagan,bhusawal
7,hugh,bangaluru
8,imad,mumbai
9,jack,chennai


In [143]:
df.drop('city', axis=1, inplace=True)

In [144]:
df.duplicated().isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [145]:
df['salary'].fillna(df['salary'].mean(), inplace=True)

In [146]:
df

,Name,Age,salary
0,Aman,22,35000.0
1,Bob,23,40000.0
2,chandan,24,45000.0
3,david,34,52500.0
4,eva,45,50000.0
5,freddy,35,55000.0
6,gagan,27,52500.0
7,hugh,26,60000.0
8,imad,29,65000.0
9,jack,30,70000.0


In [147]:
df.drop_duplicates(inplace=True)

In [148]:
df

,Name,Age,salary
0,Aman,22,35000.0
1,Bob,23,40000.0
2,chandan,24,45000.0
3,david,34,52500.0
4,eva,45,50000.0
5,freddy,35,55000.0
6,gagan,27,52500.0
7,hugh,26,60000.0
8,imad,29,65000.0
9,jack,30,70000.0
